name: gestion_livreurs
description: "A new Flutter project."
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: ^3.10.4

dependencies:
  flutter:
    sdk: flutter
  supabase_flutter: ^2.12.0
  get: ^4.7.3
  image_picker: ^1.0.7
  pdf: ^3.10.8
  printing: ^5.11.1
  intl: ^0.19.0
  path_provider: ^2.1.2
  url_launcher: ^6.1.11
  google_fonts: ^6.1.0
  icons_plus: ^5.0.0
  photo_view: ^0.14.0
  share_plus: ^7.2.1
  permission_handler: ^11.1.0
  dio: ^5.4.0

  cupertino_icons: ^1.0.8

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^6.0.0


flutter:


  uses-material-design: true


  # To add assets to your application, add an assets section, like this:
  # assets:
  #   - images/a_dot_burr.jpeg
  #   - images/a_dot_ham.jpeg



